config/routes.rb
Rails.application.routes.draw do


  resources :genres
  resource :session

  get "signin" => "sessions#new"

  get "signup" => "users#new"

  resources :users
  root "movies#index"

  get "movies/filter/:scope" => "movies#index", as: :filter_movies

  resources :movies do
    resources :reviews
    resources :favorites
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types(:danger)

private

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to signin_url, alert: "Please sign in first"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    current_user == user
  end

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access"
    end
  end

  def current_user_admin?
    current_user && current_user.admin?
  end

  def current_user_or_admin? user
    (current_user? user) || current_user_admin?
  end

  helper_method :current_user
  helper_method :current_user?
  helper_method :current_user_admin?
  helper_method :current_user_or_admin?
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    if content_for? :title
      "Movies - #{content_for :title}"
    else
      "Movies"
    end
  end

  def title(object)
    content_for(:title, object)
  end

  def nav_link_to(text, url)
    if current_page?(url)
      class1 = "button active"
    else
      class1 = "button"
    end
    link_to text, url, class: class1
  end

end

app/views/application/_aside.html.erb
<aside id="sidebar">
  <ul >
    <li>
      Movies
    </li>
    <li>
      <%= nav_link_to 'Released Movies', movies_path %>
    </li>
    <li>
      <%= nav_link_to 'Hits', filter_movies_path(:hits) %>
    </li>
    <li>
      <%= nav_link_to 'Upcoming', filter_movies_path(:upcoming) %>
    </li>
    <% if current_user_admin? %>
    <li>
      <%= nav_link_to 'Add New Movie', new_movie_path %>
    </li>

    <% end %>
  </ul>
  <ul>
    <li>
      Users
    </li>
    <li>
      <%= link_to "All Users", users_path %>
    </li>
  </ul>

<%= content_for :side %>

</aside>

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <section class="error">
    <header>
      <h2>
        Oops! You have form errors.
      </h2>
      <h3>
        Please correct the following
        <%= pluralize object.errors.count, "error" %>:
      </h3>
    </header>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/application/_flash.html.erb
<% flash.each do |k, v| %>
  <%= content_tag(:p, v, class: "flash_#{k}") %>
<% end %>

app/views/application/_footer.html.erb
<footer id="footer">
  <p>
    Created by: James Barr
  </p>
</footer>

app/views/application/_header.html.erb
<header id = "header">
  <h1>Movies</h1>
  <p>
    <% if current_user %>
      <%= link_to current_user.name, user_path(current_user) %>
      <%= link_to "Account Settings", edit_user_path(current_user) %>
      <%= link_to "Sign Out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", signin_path %>
      <%= link_to "Sign Up", signup_path %>
    <% end %>
  </p>

</header>

app/views/application/_review_movie.html.erb
<header>
  <h2>
    New Review for <%= @movie.title %>
  </h2>
</header>

<%= render 'errors', object: @review %>

<%= form_for [@movie, @review] do |f| %>
  <ul>
    <li>
      <%= f.label :stars %><br />
      <% Review::Rating_stars.each do |star| %>
        <%= f.radio_button :stars, star %> <%= star %><br />
      <% end %>
    </li>
    <li>
      <%= f.label :comment %>
      <%= f.text_area :comment, size: "20x10" %>
    </li>
    <li>
      <%= f.label :location %>
      <%= f.text_field :location %>
    </li>
  </ul>
  <%= f.submit "Create" %>
<% end %>

app/views/application/_reviews_show.html.erb
<article>
<% object.each do |r| %>
  <table>

    <p class="profile_image">
      <%= gravatar_image(r.user) %>
    </p>

    <p>
    <tr>
      <th>
        Reviewer Name
      </th>
      <td>
        <%= link_to r.user.name, r.user %>
      </td>
    </tr>
    </p>

    <p>
    <tr>
      <th>
        Stars
      </th>
      <td>
        <%= pluralize r.stars, "star" %>
      </td>
    </tr>
    </p>

    <p>
    <tr>
      <th>
        Reviewer Location
      </th>
      <td>
        <%= r.location %>
      </td>
    </tr>
    </p>

    <p>
    <tr>
      <th>
        When Reviewed
      </th>
      <td>
        <%= time_since r %>
      </td>
    </tr>
    </p>

    <p>
    <tr>
      <th>
        Comments
      </th>
      <td>
        <%= r.comment %>
      </td>
    </tr>
    </p>

  </table>
<% end %>

</article>